### Importação dos dados

In [15]:
import pandas as pd
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja = pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja.head()

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38

In [ ]:
valor_total1 = loja.groupby("Produto")['Preço'].sum().sort_values()
valor_total1.plot( kind='bar' ,figsize=(14,10), color='red')

Produto
Corda de pular                    870.89
Dinossauro Rex                    918.40
Cubo mágico 8x8                   929.27
Jogo de copos                    1812.15
Xadrez de madeira                1907.42
Dashboards com Power BI          1940.86
Blocos de montar                 2487.74
Boneca bebê                      2583.17
Ciência de dados com python      2752.18
Iniciando em programação         2791.03
Bola de vôlei                    2816.22
Pandeiro                         2985.19
Faqueiro                         3203.18
Copo térmico                     3284.68
Panela de pressão                3505.71
Bola de basquete                 3666.88
Modelagem preditiva              4229.85
Carrinho controle remoto         5015.28
Mochila                          5156.50
Headset                          6307.71
Fone de ouvido                   6725.32
Jogo de panelas                  8410.44
Smartwatch                       9936.51
Jogo de tabuleiro               10152.50
Mesa de centro                  10162.54
Assistente virtual              10744.05
Poltrona                        13172.23
Mesa de jantar                  14042.39
Kit banquetas                   16188.25
Violão                          18765.28
Cômoda                          20905.92
Impressora                      21884.23
Cadeira de escritório           23556.36
Cama box                        29459.35
Bicicleta                       36592.38
Guarda roupas                   39282.78
Fogão                           39839.30
Cama king                       41569.04
Sofá retrátil                   41839.25
Celular ABXY                    43534.47
Micro-ondas                     46348.89
Guitarra                        49722.88
Bateria                         50258.34
Tablet ABXY                     63520.11
Secadora de roupas              78749.73
Lava louças                     82739.86
Lavadora de roupas              87711.30
Smart TV                        89936.15
Celular Plus X42               130536.40
Geladeira                      149524.28
TV Led UHD 4K                  189534.28
Name: Preço, dtype: float64

#1. Análise do faturamento

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38
...,...,...,...,...,...,...,...,...,...,...,...,...
2354,Celular Plus X42,eletronicos,1712.54,88.772042,15/11/2021,Thiago Silva,RJ,1,boleto,1,-22.25,-42.66
2355,Impressora,eletronicos,377.02,20.363958,18/03/2023,Lucas Oliveira,SP,5,boleto,1,-22.19,-48.79
2356,Jogo de tabuleiro,brinquedos,163.82,9.611337,06/07/2021,Lucas Oliveira,PR,5,cartao_credito,4,-24.89,-51.55
2357,Cama box,moveis,921.77,46.665919,02/05/2022,Pedro Gomes,RN,1,cartao_credito,2,-5.81,-36.59
2358,Smartwatch,eletronicos,259.95,11.425995,18/06/2022,Felipe Santos,RS,4,cartao_credito,1,-30.17,-53.50

KeyError: ('Vendedor', 'Frete')

# 2. Vendas por Categoria

# 3. Média de Avaliação das Lojas

# 4. Produtos Mais e Menos Vendidos

# 5. Frete Médio por Loja